"""Remove image_file from users and encryption_key from notes

Revision ID: 1375b660a402
Revises: fe5f10f61c02
Create Date: 2025-01-13 15:52:50.009371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1375b660a402'
down_revision = 'fe5f10f61c02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('encryption_key')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('image_file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.VARCHAR(length=20), nullable=False))

    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encryption_key', sa.VARCHAR(length=44), nullable=True))

    # ### end Alembic commands ###
